### ISSUE TITLE
Merge Google Doc "fork" of "First Lesson Publishing" back into source markdown

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-101-guide#17]
A while ago a "fork" of this repo was made in [a Google doc](https://docs.google.com/document/d/1F2g4BbOqQ0vveCyPD6twkSsNNi6b9_18mUd8YbtOpL8). Suggestions were left and changes were made but they were never merged back into this repo's source. Let's get them merged in so instructor.egghead.io/guide can have the improvements.

**Comment by joelhooks** [comment]
That google doc can be ignored in favor of https://paper.dropbox.com/folder/show/Instructor-Guide-e.iX7ZavGxujPFwhjOZcQs9puOKxeyvKJv1Ic76Y3DOIWYWzK8Vr

**Comment by trevordmiller** [comment]
Ok, can we keep this issue open to get that merged into source?

**Comment by trevordmiller** [comment]
nevermind, just saw https://github.com/eggheadio/egghead-instructor-101-guide/issues/19
