### ISSUE TITLE
Replace GitBook for book creation

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-101-guide#18]
Currently we are using [GitBook](https://www.gitbook.com/) to create the instructor guide, which gets published to https://instructor.egghead.io/guide/. It could be useful to build our own open source package that generates an app from directories of markdown files.

**Comment by trevordmiller** [comment]
Idea: It would be nice if there was no config; so like [next.js](https://github.com/zeit/next.js/), we could have a "pages" directory which renders markdown files in the hierarchy they are defined in the system.

**Comment by joelhooks** [comment]
I'm going to table this for now as it isn't high-priority and doesn't bring a lot of value in relation to the expense/effort. This is going to stay a book for the time being.

**Comment by trevordmiller** [comment]
No worries. Had this on my notes from our discussions a couple weeks ago, but will close for now.
