### ISSUE TITLE
Update guide with current sections

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-instructor-101-guide#19]
The current text for the guide update [can be found here in Paper](https://paper.dropbox.com/folder/show/Instructor-Guide-e.iX7ZavGxujPFwhjOZcQs9puOKxeyvKJv1Ic76Y3DOIWYWzK8Vr).

It is divided into more cohesive sections, that will facilitate a more "article style" approach to adding content to the guide. The sections are effectively "tags" to organize the various articles.

The Paper document is effectively for staging and discussion. Paper will allow us to save individual files as markdown, and those will stored here on github for delivery.

This is the major drawback to using Paper, but is a better venue for document discussion than github PRs for documents. 

Improvement suggestions to the proposed process are welcome.

## What needs to get done

Compare the sections and articles described here between [the Paper document](https://paper.dropbox.com/folder/show/Instructor-Guide-e.iX7ZavGxujPFwhjOZcQs9puOKxeyvKJv1Ic76Y3DOIWYWzK8Vr) and the [published sections and articles](https://github.com/eggheadio/egghead-instructor-101-guide).

Replace the markdown in the repository with the exported markdown from Paper.

## Resources

This is analysis of the (roughly) first half of [the existing currently published instructor guide](https://instructor.egghead.io/guide): https://docs.google.com/document/d/1F2g4BbOqQ0vveCyPD6twkSsNNi6b9_18mUd8YbtOpL8/edit

This is a Mindmanager Mindmap of the overall instructor guide: [Egghead.io Instructor's Guide Mindmap.zip](https://github.com/eggheadio/egghead-instructor-101-guide/files/862227/Egghead.io.Instructor.s.Guide.Mindmap.zip)

**Comment by tayiorbeii** [comment]
PR at https://github.com/eggheadio/egghead-instructor-101-guide/pull/20

**Comment by trevordmiller** [comment]
@tayiorbeii Little tip: if you add `resolve #{issue}` to your commit / squashed final commit it will auto-close the related issue.
