### ISSUE TITLE
Information on release schedules

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-101-guide#25]
The thing I get asked the most out of anything else is "when is my course going to be released"? 

We could write an article describing the process as it is now in an article and create a discrete link to it published inside of the instructor guide. This will give us a direct link to the FAQ. We can also include a summary and a link in our instructor onboarding emails.

**Comment by trevordmiller** [comment]
Paper doc ready for discussion: https://paper.dropbox.com/doc/FAQ-tshwGo7Po2ks0EBJK8BJV

**Comment by tayiorbeii** [comment]
Updated [Paper doc for Instructor Lifecycle Email](https://paper.dropbox.com/doc/SE02_02-Choose-a-lesson-topic-SfXt0USTDNFHgi1kvfVMv) for discussion, and will migrate to Drip when done.
